using System;
using System.Collections.Concurrent;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using AggregatR.Command;
using AggregatR.DI;

namespace AggregatR.Event
{
    /// <summary>
    /// This class is used by the <see cref="CommandProcessor{TIdentifier, TCommandBase, TEventBase}"/> for dispatching events.
    /// </summary>
    /// <typeparam name="TEventBase">The event base type.</typeparam>
    public class EventDispatcher<TEventBase> : IEventDispatcher<TEventBase>
    {
        private readonly ConcurrentDictionary<Type, MethodInfo> _dispatchEventMethodCache = new ConcurrentDictionary<Type, MethodInfo>();
        private readonly IServiceScopeFactory _serviceScopeFactory;

        /// <summary>
        /// Constructs a new <see cref="EventDispatcher{TEventBase}"/> instance.
        /// </summary>
        /// <param name="serviceScopeFactory">The service scope factory.</param>
        public EventDispatcher(IServiceScopeFactory serviceScopeFactory)
        {
            _serviceScopeFactory = serviceScopeFactory ?? throw new ArgumentNullException(nameof(serviceScopeFactory));
        }

        /// <summary>
        /// Called when zero or more events need to be dispatched during the handling of a single command.
        /// </summary>
        /// <param name="events">The events generated by the execution of a single command.</param>
        /// <returns>An awaitable <see cref="Task"/>.</returns>
        public async Task Dispatch(TEventBase[] events)
        {
            foreach (var @event in events ?? Array.Empty<TEventBase>())
            {
                var dispatchEventMethod = _dispatchEventMethodCache.GetOrAdd(@event.GetType(), type =>
                    GetType()
                        .GetMethod(nameof(DispatchEvent), BindingFlags.NonPublic | BindingFlags.Instance)
                        .MakeGenericMethod(type));

                await ((Task)dispatchEventMethod.Invoke(this, new object[] { @event })).ConfigureAwait(false);
            }
        }

        private async Task DispatchEvent<TEvent>(TEvent @event)
        {
            using (var serviceScope = _serviceScopeFactory.CreateScope())
            {
                var handlers = serviceScope.GetServices<IEventHandler<TEvent>>();
                foreach (var handler in handlers ?? Enumerable.Empty<IEventHandler<TEvent>>())
                    await handler.Handle(@event).ConfigureAwait(false);
            }
        }
    }
}
